---
title: "extra2"
format: html
editor: visual
---

```{r, message=F}
if(!require(readr)){install.packages("readr");library(readr)}
if(!require(dplyr)){install.packages("dplyr");library(dplyr)}
if(!require(ggplot2)){install.packages("ggplot2");library(ggplot2)}
if(!require(ggthemes)){install.packages("ggthemes");library(ggthemes)}
if(!require(ggrepel)){install.packages("ggrepel");library(ggrepel)}
if(!require(tidyverse)){install.packages("tidyverse");library(tidyverse)}
if(!require(forcats)){install.packages("forcats");library(forcats)}
if(!require(ggmosaic)){install.packages("ggmosaic");library(ggmosaic)}
if(!require(fitdistrplus)){install.packages("fitdistrplus");library(fitdistrplus)}
if(!require(rriskDistributions)){install.packages("rriskDistributions");library(rriskDistributions)}
if(!require(fastGraph)){install.packages("fastGraph")};library(fastGraph)
if(!require(dplyr)){install.packages("dplyr");library(dplyr)}
```


```{r}
DF <- read_csv("DataLimpia.csv"
               , col_types = cols(.default = col_guess()
                                  , CHIP=col_factor(levels = c("2G","3G","4G"))
                                  , PERIODO=col_date(format = "%Y%m")
                                  )
               )
```

```{r}
tiempo <- DF$TIEMPO_LLAMADAS_IN_TOT
DF$DIAS_LLAMADAS_IN_TOT
```

```{r}
hist(DF$DIAS_LLAMADAS_IN_TOT, prob = TRUE)
```

```{r}
X <- DF$DIAS_LLAMADAS_IN_TOT[!is.na(DF$DIAS_LLAMADAS_IN_TOT)]

descdist(X
         , discrete = TRUE
)
```

```{r}
FD <- fitdist(X, "pois")
```
```{r}
FD
```
```{r}
summary(FD)
plot(FD)
```

```{r}
FD2 <- fitdist(X, "nbinom")
```
```{r}
summary(FD2)
```

```{r}
plot(FD2)
```

```{r}
Y <- X
hist(Y)
Z <- runif(Y, -0.5, 0.5)
Y <- Y + Z
```

```{r}
all(round(Y) == X) 
```

```{r}
min(Y)
max(Y)
```

```{r}
W <- (Y+0.5)/32
```

```{r}
hist(Y, prob = TRUE)
```

```{r}
hist(W, prob = TRUE)
```






```{r}
FD3 <- fitdist(W, "beta"
               , method = "mle"
#               , method = "mme"
               , start = list(shape1 = 4, shape2 = 1.2)
               , lower = 1
               , upper = 5
               )
```


```{r}
summary(FD3)
```
```{r}
plot(FD3)
```
```{r}
GOF3 <- gofstat(FD3, fitnames = "beta")
```

```{r}
GOF3
```

```{r}
FD3$
```

```{r}
which(table(W)>1)
```

```{r}
table(W)[table(W)>1]
```

```{r}
which(abs(W - 0.931969977609697) < 10^(-15))
```

```{r}
W[307818] <- W[307818] + 10^(-14)
```

```{r}
which(abs(W - 0.931969977609697) < 10^(-15))
```


```{r}
ks.test(W, pbeta, FD3$estimate[1], FD3$estimate[2])
```


```{r}
data(toxocara)
number <- toxocara$number

fitp <- fitdist(number,"pois")
summary(fitp)
plot(fitp)

fitnb <- fitdist(number,"nbinom")
summary(fitnb)
plot(fitnb)

gofstat(list(fitp, fitnb),fitnames = c("Poisson","negbin"))

```



```{r}
hist(W, prob = TRUE, breaks = 50)
Xs <- seq(0, 1, 0.001)
lines(Xs, dbeta(Xs, FD3$estimate[1], FD3$estimate[2]), col = "red")
```


```{r}
dbet
```


```{r}
? fitdist
```

