---
title: "LimpiezaDatos"
format: html
---

## Cargando los datos

```{r}
library(readr)
library(dplyr)
```

```{r charge-databases, message=FALSE}
rm(list = ls())
DF1 <- read_delim("data/EQUIPOS.txt","|")
DF2 <- read_delim("data/CONSULTAS_PORTA.txt","|")
DF3 <- read_delim("data/FACTURACION.txt","|")
DF4 <- read_delim("data/INDICADORES_RED.txt","|")
DF5 <- read_delim("data/INTENTOS_PORTA.txt","|")
DF6 <- read_delim("data/PLANTA.txt","|")
DF7 <- read_delim("data/TARGET.txt","|")
DF8 <- read_delim("data/TRAFICO_DATOS.txt","|")
DF9 <- read_delim("data/TRAFICOVOZSMS.txt","|")
```

### Limpieza 1

```{r}
data1 <- left_join(DF1,DF8, by = c("ID1", "PERIODO"))
data1 %>% subset(select = -c(TRAF_DATOS_3G_NO_COSITE,TRAF_DATOS_3G_COSITE)) -> data1


temp1 <- DF6[, c("ID1", "PERIODO", "DEPARTAMENTO_XDR", "DEPARTAMENTO_CDR")]
data2 <- left_join(data1,temp1, by=c("ID1","PERIODO"))
```

## Limpieza 2

```{r}
temp2 <- subset(DF9,select = -c(
  CALLS_OUT_ON,
  CALLS_OUT_OFF,
  DEST_VOICE_ON,
  DEST_VOICE_OFF,
  DAYS_OUT_VOICE_ON,
  DAYS_OUT_VOICE_OFF,
  CONT_ON,
  CONT_OFF,
  TOP_CONT_ON_5,
  TOP_CONT_OFF_5,
  CALLS_OUT_ON,
  CALLS_OUT_OFF,
  DEST_VOICE_ON,
  AIRTIME_IN_ON,
  AIRTIME_IN_OFF,
  CALLS_IN_ON,
  CALLS_IN_OFF,
  ORIG_VOICE_ON,
  ORIG_VOICE_OFF,
  DAYS_IN_VOICE_ON,
  DAYS_IN_VOICE_OFF,
  AIRTIME_OUT_ON,
  AIRTIME_OUT_OFF
))



data3 <- left_join(data2, temp2, by=c("ID1", "PERIODO"))
```

## Limpieza 3

```{r}
data3 %>% rename(ID = ID1,
         CHIP = EQUIPO_TEC,
         MARCA = EQUIPO_MARCA,
         MODELO = EQUIPO_MODELO,
         OS = EQUIPO_OS,
         DATOS_4G = TRAF_DATOS_4G,
         DATOS_3G = TRAF_DATOS_3G,
         DATOS_2G = TRAF_DATOS_2G,
         DATOS_TOTAL = TRAF_DATOS_TOTAL,
         TIEMPO_4G = TRAF_DURACION_4G,
         TIEMPO_3G = TRAF_DURACION_3G,
         TIEMPO_2G = TRAF_DURACION_2G,
         DPTO_DATOS = DEPARTAMENTO_XDR,
         DPTO_TIEMPO_LLAMADAS = DEPARTAMENTO_CDR,
         TIEMPO_LLAMADAS_IN_TOT = AIRTIME_IN_TOT,
         TIEMPO_LLAMADAS_IN_SEM = AIRTIME_IN_WEEK,
         TIEMPO_LLAMADAS_IN_FINDE = AIRTIME_IN_WEEKD,
         LLAMADAS_IN_TOT = CALLS_IN_TOT,
         LLAMADAS_IN_SEM = CALLS_IN_WEEK,
         LLAMADAS_IN_FINDE = CALLS_IN_WEEKD,
         TIEMPO_LLAMADAS_OUT_TOT = AIRTIME_OUT_TOT,
         TIEMPO_LLAMADAS_OUT_SEM = AIRTIME_OUT_WEEK,
         TIEMPO_LLAMADAS_OUT_FINDE = AIRTIME_OUT_WEEKD,
         LLAMADAS_OUT_TOT = CALLS_OUT_TOT,
         LLAMADAS_OUT_SEM = CALLS_OUT_WEEK,
         LLAMADAS_OUT_FINDE = CALLS_OUT_WEEKD,
         CONTACTOS_LLAMADAS_IN_TOT = ORIG_VOICE_TOT,
         CONTACTOS_LLAMADAS_OUT_TOT = DEST_VOICE,
         DIAS_LLAMADAS_IN_TOT = DAYS_IN_VOICE_TOT,
         DIAS_LLAMADAS_OUT_TOT = DAYS_OUT_VOICE_TOT,
         CONTACTOS_TOT = CONT_TOT,
         CONTACTOS_TOT_5 = TOP_CONT_5,
         ) -> data4
```

```{r}
orden_corregido <- c(
  "ID",
  "PERIODO",
  "CHIP",
  "MARCA",
  "MODELO",
  "OS",
  "DATOS_4G",
  "DATOS_3G",
  "DATOS_2G",
  "DATOS_TOTAL",
  "TIEMPO_4G",
  "TIEMPO_3G",
  "TIEMPO_2G",
  "DPTO_DATOS",
  "DPTO_TIEMPO_LLAMADAS",
  "TIEMPO_LLAMADAS_IN_TOT",
  "TIEMPO_LLAMADAS_IN_SEM",
  "TIEMPO_LLAMADAS_IN_FINDE",
  "LLAMADAS_IN_TOT",
  "LLAMADAS_IN_SEM",
  "LLAMADAS_IN_FINDE",
  "TIEMPO_LLAMADAS_OUT_TOT",
  "TIEMPO_LLAMADAS_OUT_SEM",
  "TIEMPO_LLAMADAS_OUT_FINDE",
  "LLAMADAS_OUT_TOT",
  "LLAMADAS_OUT_SEM",
  "LLAMADAS_OUT_FINDE",
  "CONTACTOS_LLAMADAS_IN_TOT",
  "CONTACTOS_LLAMADAS_OUT_TOT",
  "DIAS_LLAMADAS_IN_TOT",
  "DIAS_LLAMADAS_OUT_TOT",
  "CONTACTOS_TOT",
  "CONTACTOS_TOT_5"
)

data5 <- data4[, orden_corregido]
```


```{r}
write.csv(data5, "DataLimpia.csv", row.names = FALSE)
round(sum(is.na(data5))/(nrow(data5)*ncol(data5))*100 , digits = 2)
```

```{r}
#str(data5)
length(data5$ID[duplicated(data5$ID)])
nrow(data5)
xd <- data5[complete.cases(data5),]
xd$PERIODO
frec <- table(xd$PERIODO)
barplot(frec)
nrow(data5)
sum(complete.cases(data5))
rm(list = ls())
```

